### ISSUE TITLE
Add an option to export diagrams as PDF/JPG/PNG

### ISSUE THREAD

**Issue by iamcrowd** [iamcrowd/crowd-app#2]
It would be nice to save our models as PDF/JPG/PNG

**Comment by giuliano-marinelli** [comment]
Solved at [https://github.com/iamcrowd/crowd-app/commit/bda49ea2ca4ddd9abf2d942e12428fcdbb58d0f5](https://github.com/iamcrowd/crowd-app/commit/bda49ea2ca4ddd9abf2d942e12428fcdbb58d0f5)
